### PR TITLE
feat: Add extra tags to Sentry and modernize SentryReporterAdapter

### PR DESCRIPTION
**Pull request by tcitworld**
- Add email to user context
- instance_url for context (especially useful for cron job issues)
- instance_name for extra context

### CODE REVIEW

**Comment by tcitworld** [comment]
CI blocked by https://github.com/ChristophWurst/nextcloud_sentry/pull/520 and other CI stuff

**Comment by ChristophWurst** [comment]
@tcitworld rebase

**Comment by ChristophWurst** [comment]
https://github.com/ChristophWurst/nextcloud_sentry/pull/540 should fix CI. The "fix" is not very profound but I'm currently unable to come up with a better solution.

**Comment by tcitworld** [comment]
Rebased, pending workflow approval

**Comment by ChristophWurst** [comment]
Added you as a collaborator :pray:

**Pull request merged**
